# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NasaDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SwiftLint'
    pod 'Nuke', '~> 9.0'
    pod 'Lightbox', '~> 2.4.2'
    pod 'Toast-Swift', '~> 5.0.1'

  # Pods for NasaDemo

  target 'NasaDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NasaDemoUITests' do
    # Pods for testing
  end

end
